name: Deploy Backend via Frontend Bastion

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload deploy-backend.sh to Frontend EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FRONTEND_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          port: 22
          source: "deploy-backend.sh"
          target: "~/"
          timeout: "600s"

      - name: Trigger backend deploy from Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.FRONTEND_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          script: |
            export BACKEND_REPO_URL="${{ secrets.BACKEND_REPO_URL }}"
            export RDS_ENDPOINT="${{ secrets.RDS_ENDPOINT }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export LOCATIONIQ_API_KEY="${{ secrets.LOCATIONIQ_API_KEY }}"
            chmod +x ~/deploy-backend.sh
            ~/deploy-backend.sh

