name: Deploy Backend via Bastion

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload deploy script to frontend EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FRONTEND_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          source: "./deploy-backend.sh"
          target: "~/"

      - name: Run script to SSH into backend and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FRONTEND_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_EC2_KEY }}
          script: |
            chmod +x ~/deploy-backend.sh
            ./deploy-backend.sh
