name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload deploy-backend.sh a EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.APP_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.APP_EC2_KEY }}
          port: 22
          source: "deploy-backend.sh"
          target: "~/"
          timeout: "600s"

      - name: Ejecutar deploy en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.APP_EC2_KEY }}
          script: |
            export RDS_ENDPOINT="${{ secrets.RDS_ENDPOINT }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export LOCATIONIQ_API_KEY="${{ secrets.LOCATIONIQ_API_KEY }}"
            export CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}"
            export CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}"
            export CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}"
            chmod +x ~/deploy-backend.sh
            ~/deploy-backend.sh

